import io
import logging
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from app.models.grocery_item import GroceryItem
from app.models.reflection import Reflection
from app.services.prediction_service import predict_consumption

logger = logging.getLogger(__name__)


def generate_weekly_pdf_report(db: Session) -> bytes:
    """Generates a weekly PDF report of grocery inventories, reflections, and predictions."""
    logger.info("Generating weekly PDF report...")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        name="TitleStyle",
        parent=styles["Title"],
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1A365D"),
        spaceAfter=15
    )
    subtitle_style = ParagraphStyle(
        name="SubtitleStyle",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=10,
        spaceAfter=10
    )
    body_style = styles["Normal"]

    # Header section
    story.append(Paragraph("Weekly Household Grocery Report", title_style))
    story.append(Paragraph("Generated by KinNest Mother Agent", body_style))
    story.append(Spacer(1, 15))

    # Reflections Section
    story.append(Paragraph("Kitchen Reflections & Insights", subtitle_style))
    reflections = db.query(Reflection).order_by(Reflection.created_at.desc()).limit(3).all()
    if not reflections:
        story.append(Paragraph("No reflections logged for this week.", body_style))
    else:
        for r in reflections:
            story.append(Paragraph(f"• <b>{r.item_name}</b>: {r.insight} (Rec: {r.recommendation})", body_style))
    story.append(Spacer(1, 15))

    # Inventory Table Section
    story.append(Paragraph("Current Inventory & Weekly Forecasts", subtitle_style))
    
    # Table headers
    data = [["Item", "Stock", "Unit", "Daily Est.", "Weekly Forecast", "Buy Recommended"]]
    
    items = db.query(GroceryItem).all()
    for item in items:
        pred = predict_consumption(db, item.name)
        daily_use = pred.get("predicted_daily_usage", 0.0) if "error" not in pred else 0.0
        weekly_req = pred.get("next_7_days_requirement", 0.0) if "error" not in pred else 0.0
        to_buy = pred.get("recommended_purchase", 0.0) if "error" not in pred else 0.0
        
        data.append([
            item.name,
            f"{item.quantity:.1f}",
            item.unit or "",
            f"{daily_use:.2f}",
            f"{weekly_req:.1f}",
            f"{to_buy:.1f}"
        ])

    if len(data) == 1:
        story.append(Paragraph("No inventory items found.", body_style))
    else:
        t = Table(data, colWidths=[120, 60, 60, 80, 100, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2B6CB0")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#F7FAFC")),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
            ('FONTSIZE', (0,0), (-1,-1), 9),
        ]))
        story.append(t)

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()

    logger.info("PDF report generation complete.")
    return pdf_data
