import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { aiService, Alert } from '../services/aiService';
import { shoppingService } from '../services/shoppingService';
import { AlertCircle, AlertTriangle, Info, Bell, Check, Loader2 } from 'lucide-react';

export const Alerts: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [resolvingId, setResolvingId] = useState<string | null>(null);

  const loadAlerts = async () => {
    setLoading(true);
    try {
      const data = await aiService.getAlerts();
      setAlerts(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const handleActionClick = async (alertItem: Alert) => {
    setResolvingId(alertItem.id);
    try {
      // Perform actions based on type
      if (alertItem.actionType === 'add_rice') {
        await shoppingService.addShoppingItem({
          name: 'Sona Masoori Rice',
          quantity: 5,
          unit: 'kg',
          category: 'Staples',
          estimatedPrice: 325,
          priority: 'Must Buy',
          aiReason: 'Rice depletion warning resolution.',
          checked: false
        });
      } else if (alertItem.actionType === 'create_meal_plan') {
        navigate('/meal');
        return;
      } else if (alertItem.actionType === 'view_budget') {
        navigate('/insights');
        return;
      }

      // Mark resolved in service
      await aiService.resolveAlert(alertItem.id);
      setAlerts(prev => prev.map(a => a.id === alertItem.id ? { ...a, resolved: true } : a));
    } catch (err) {
      console.error(err);
    } finally {
      setResolvingId(null);
    }
  };

  const getAlertStyle = (type: string, resolved: boolean) => {
    if (resolved) return 'bg-slate-50 border-slate-200 opacity-60 text-slate-500';
    switch (type) {
      case 'critical':
        return 'bg-rose-50/75 border-rose-150 text-rose-800';
      case 'warning':
        return 'bg-amber-50/75 border-amber-150 text-amber-800';
      case 'info':
      default:
        return 'bg-blue-50/75 border-blue-150 text-blue-800';
    }
  };

  const getAlertIcon = (type: string, resolved: boolean) => {
    if (resolved) return <Check className="h-5 w-5 text-slate-400" />;
    switch (type) {
      case 'critical':
        return <AlertCircle className="h-5 w-5 text-rose-500 shrink-0" />;
      case 'warning':
        return <AlertTriangle className="h-5 w-5 text-amber-500 shrink-0 animate-pulse" />;
      case 'info':
      default:
        return <Info className="h-5 w-5 text-indigo-500 shrink-0" />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-800">Proactive Agent Alerts</h1>
        <p className="text-slate-500 font-medium text-xs mt-1">Real-time alerts generated by the Mother Agent regarding stock, budgets, and waste reduction.</p>
      </div>

      {loading ? (
        <div className="flex h-40 items-center justify-center">
          <Loader2 className="h-8 w-8 animate-spin text-indigo-600" />
        </div>
      ) : (
        <div className="space-y-4">
          {alerts.map((alertItem) => (
            <div 
              key={alertItem.id} 
              className={`
                flex flex-col md:flex-row md:items-center justify-between rounded-2xl border p-5 transition-all shadow-2xs
                ${getAlertStyle(alertItem.type, alertItem.resolved)}
              `}
            >
              <div className="flex items-start gap-3.5">
                {getAlertIcon(alertItem.type, alertItem.resolved)}
                <div>
                  <h3 className={`font-bold text-sm ${alertItem.resolved ? 'text-slate-400 line-through' : 'text-slate-800'}`}>
                    {alertItem.title}
                  </h3>
                  <p className={`text-xs font-semibold mt-1 leading-normal ${alertItem.resolved ? 'text-slate-400' : 'text-slate-500'}`}>
                    {alertItem.message}
                  </p>
                </div>
              </div>

              <div className="mt-4 md:mt-0 flex justify-end gap-3 border-t border-slate-200/40 pt-3 md:border-none md:pt-0">
                {!alertItem.resolved ? (
                  <button 
                    onClick={() => handleActionClick(alertItem)}
                    disabled={resolvingId === alertItem.id}
                    className="flex items-center gap-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 disabled:bg-slate-600 text-white px-4.5 py-2.5 text-xs font-bold transition-all cursor-pointer shadow-xs"
                  >
                    {resolvingId === alertItem.id ? <Loader2 className="h-3 w-3 animate-spin" /> : null}
                    {alertItem.actionLabel}
                  </button>
                ) : (
                  <span className="flex items-center gap-1 text-[11px] font-bold text-slate-400 bg-slate-100/80 px-3 py-1.5 rounded-lg border border-slate-200/50">
                    <Check className="h-3 w-3" />
                    Resolved
                  </span>
                )}
              </div>
            </div>
          ))}

          {alerts.length === 0 && (
            <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 bg-white py-12 px-4 text-center">
              <Bell className="h-8 w-8 text-slate-350" />
              <h3 className="mt-4 text-lg font-bold text-slate-800">Your feed is clear</h3>
              <p className="mt-1 text-sm text-slate-500">No proactive alerts require resolution today.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
export default Alerts;
