import React, { useEffect, useState } from 'react';
import { Bell, ChevronRight, CheckCircle, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { db } from '../data/mockData';

const ALERT_CONFIG = {
  danger:  { dotColor: 'bg-rose-500',   barColor: 'border-rose-200 bg-rose-50',   labelBg: 'bg-rose-100 text-rose-700',   icon: '🔴' },
  warning: { dotColor: 'bg-amber-500',  barColor: 'border-amber-200 bg-amber-50', labelBg: 'bg-amber-100 text-amber-700', icon: '🟡' },
  success: { dotColor: 'bg-emerald-500',barColor: 'border-emerald-200 bg-emerald-50', labelBg: 'bg-emerald-100 text-emerald-700', icon: '🟢' },
};

function formatTime(iso: string) {
  return new Date(iso).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', hour12: true });
}

export default function Alerts() {
  const navigate = useNavigate();
  const [alerts, setAlerts] = useState([...db.alerts]);

  const markRead = (id: string) => {
    setAlerts((prev) => prev.map((a) => a.id === id ? { ...a, read: true } : a));
    const idx = db.alerts.findIndex((a) => a.id === id);
    if (idx !== -1) db.alerts[idx].read = true;
  };

  const unread = alerts.filter((a) => !a.read);
  const read   = alerts.filter((a) => a.read);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-slate-900">AI Alerts</h1>
          <p className="text-sm text-slate-500 mt-0.5">Smart notifications generated by Baby Care Agent</p>
        </div>
        {unread.length > 0 && (
          <span className="rounded-full bg-rose-100 px-3 py-1 text-xs font-bold text-rose-700">
            {unread.length} Unread
          </span>
        )}
      </div>

      {/* Unread */}
      {unread.length > 0 && (
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-3">New · Needs Attention</h3>
          <div className="space-y-3">
            {unread.map((alert) => {
              const cfg = ALERT_CONFIG[alert.type as keyof typeof ALERT_CONFIG];
              return (
                <div key={alert.id} className={`relative flex items-start gap-4 rounded-2xl border p-4 ${cfg.barColor}`}>
                  <div className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${cfg.dotColor} animate-pulse`} />
                  <div className="flex-1">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-semibold text-slate-800">{cfg.icon} {alert.message}</p>
                      <span className={`shrink-0 rounded-full px-2.5 py-0.5 text-[10px] font-bold ${cfg.labelBg}`}>
                        {alert.type.charAt(0).toUpperCase() + alert.type.slice(1)}
                      </span>
                    </div>
                    <p className="text-xs text-slate-400 mt-1">{formatTime(alert.timestamp)}</p>
                    <div className="mt-3 flex gap-2">
                      <button
                        onClick={() => navigate(alert.route)}
                        className="flex items-center gap-1 rounded-lg bg-slate-800 px-3 py-1.5 text-xs font-semibold text-white hover:bg-slate-700 transition-colors"
                      >
                        View Details <ChevronRight className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => markRead(alert.id)}
                        className="flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50 transition-colors"
                      >
                        <CheckCircle className="h-3.5 w-3.5" />
                        Mark Read
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Read */}
      {read.length > 0 && (
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-3">Resolved / Read</h3>
          <div className="space-y-2">
            {read.map((alert) => {
              const cfg = ALERT_CONFIG[alert.type as keyof typeof ALERT_CONFIG];
              return (
                <div key={alert.id} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-white p-4 opacity-70 hover:opacity-100 transition-opacity">
                  <div className={`h-2 w-2 shrink-0 rounded-full ${cfg.dotColor}`} />
                  <div className="flex-1">
                    <p className="text-sm font-medium text-slate-600">{alert.message}</p>
                    <p className="text-xs text-slate-400 mt-0.5">{formatTime(alert.timestamp)}</p>
                  </div>
                  <button
                    onClick={() => navigate(alert.route)}
                    className="shrink-0 text-xs font-medium text-violet-600 hover:underline flex items-center gap-1"
                  >
                    View <ChevronRight className="h-3 w-3" />
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {alerts.length === 0 && (
        <div className="flex flex-col items-center py-16 text-center">
          <Bell className="h-12 w-12 text-slate-200 mb-3" />
          <p className="text-sm font-medium text-slate-500">No alerts at the moment.</p>
          <p className="text-xs text-slate-400 mt-1">Baby Care Agent will notify you of important updates.</p>
        </div>
      )}

      {/* AI Note */}
      <div className="flex items-start gap-3 rounded-2xl border border-violet-100 bg-violet-50 p-4">
        <Info className="h-5 w-5 text-violet-600 shrink-0 mt-0.5" />
        <p className="text-xs text-violet-700">
          All alerts are generated by Baby Care Agent based on real-time analysis of Aarav's feeding, sleep, growth, health, and vaccination data.
        </p>
      </div>
    </div>
  );
}
